version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    platform: linux/amd64
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-nestuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nestpass}
      POSTGRES_DB: ${DB_NAME:-biro_db}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_USERNAME:-nestuser} -d ${DB_NAME:-biro_db}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
