export const REALTIME_RECONNECT_GRACE_MS = 3000;
export const REALTIME_DEDUP_TTL_MS = 60_000;
export const REALTIME_BULL_ATTEMPTS = 3;
export const PENDING_SWEEP_INTERVAL_MS = 1000;
export const REALTIME_PENDING_TTL_SECONDS = 10; // 10 seconds
export const REALTIME_JOB_TTL_SECONDS = 300;
