name: Deploy NestJS to GCP

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build & Push Docker Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-app:$GITHUB_SHA
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nestjs-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-app:$GITHUB_SHA \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars \
              MODE=${{ secrets.MODE }},\
              DB_HOST=${{ secrets.DB_HOST }},\
              DB_PORT=${{ secrets.DB_PORT }},\
              DB_USERNAME=${{ secrets.DB_USERNAME }},\
              DB_PASSWORD=${{ secrets.DB_PASSWORD }},\
              DB_NAME=${{ secrets.DB_NAME }},\
              REDIS_HOST=${{ secrets.REDIS_HOST }},\
              REDIS_PORT=${{ secrets.REDIS_PORT }},\
              REDIS_DB_INDEX=${{ secrets.REDIS_DB_INDEX }},\
              REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }},\
              FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }},\
              FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }},\
              FIREBASE_PRIVATE_KEY="${{ secrets.FIREBASE_PRIVATE_KEY }}"
